services:
  fastapi-app:
    build: ./src/backend
    container_name: fastapi-container
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env
    volumes:
      - ./markdown:/app/markdown
    develop:
      watch:
        - action: sync
          path: ./src/backend/src
          target: /app
  docusaurus:
    build:
      context: ./src/app
      target: ${TARGET:-development}
    ports:
      - "3000:3000"
      - "80:80"
    depends_on:
      - fastapi-app
      - phpmyadmin
    environment:
      - NODE_ENV=${TARGET:-development}
    volumes:
      - ./markdown/tutorial:/app/docs/tutorial
  db:
    image: mariadb:lts
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mariadb-admin ping -h localhost -p${MARIADB_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-data:
